### PR TITLE
stick to the REST syntax

### PR DESCRIPTION
**Pull request by franzholz**

### CODE REVIEW

**Comment by garvinhicking** [comment]
All the current documentation manuals use the current syntax for this when embedding a "table of contents", this would be a "breaking change" for them. At least we would then need PR's/changes for all the TYPO3-Documentation Repositories to change that, too.

What would be your reasoning to change that, there should be a benefit in doing this? Semantically it would change the TOC to be a headline segment, but I'm not really sure that this rectifies its own structural entry, when the start page already basically is a "table of contents" and its headline reflects the title of the document?

**Comment by franzholz** [comment]
All the RST files of TYPO3CMS-Example-ExtensionManual use this headline format:


```
============
Introduction
============
```

Therefore also the  Index.rst file should use the same. 

Alternatively a smaller headline could be used here as in


```
What does it do?
================

```

**Comment by garvinhicking** [comment]
Yes, but the TOC is not really a headline, so currently it's not formatted as one, and just as a bold text... which IMO isn't wrong per se?! If we would create this from scratch we could argue changing that, but doing that now with so many documentation formats out there, that would create a different layout experience. I'd argue the benefits of changing it semantically to a headline do not outweigh the Breaking Change and resulting "mess" of different implementations.

**Comment by franzholz** [comment]
Why should there be a problem with the header in TOC with any other documentation formats`? The TOC is not created  fully automatically.  All the TOC lines are inserted. It is only the toctree format which is relevant and must fit to the header.

**Comment by franzholz** [comment]
Shouldn't all headers of a document look the same? The table of contents is a header even if it is now written in bold letters. I see no advantage in having a different header format than in the rest of the document here.

**Comment by garvinhicking** [comment]
> Shouldn't all headers of a document look the same? The table of contents is a header even if it is now written in bold letters. I see no advantage in having a different header format than in the rest of the document here.

Yes, all headers should look the same - IF they are headers. Currently, the TOC is *NOT* a header - and that's what my point is. If we change that, we change the layout. But not for existing documentation, but only for new documentations build with this example as a template. We would have to change each and every single documentation out there (most not by us but by other authors) to make it "in synch" again.

That's why I'm saying, the benefit is IMO not worth the drawbacks of non-uniform documentation looks.

This is my opinion on the matter, I'll wait now for someone else of the documentation team to chime to make a decision 🫣

**Comment by linawolf** [comment]
There must only be one h1 headline per file. your change would introduce a second one. 

Also this is not a real headline as it is not a section of the page. We might switch to using a caption later on, but the current status quo already contains valid reST.

**Comment by franzholz** [comment]
It is the header of a list of TOC entries. So it is really a header, but only shown as bold text.

**Pull request closed without merging**
